// Code generated by ent, DO NOT EDIT.

package blogs

const (
	// Label holds the string label denoting the blogs type in the database.
	Label = "blogs"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBlogTitle holds the string denoting the blogtitle field in the database.
	FieldBlogTitle = "blog_title"
	// FieldBlogType holds the string denoting the blogtype field in the database.
	FieldBlogType = "blog_type"
	// FieldBlogContent holds the string denoting the blogcontent field in the database.
	FieldBlogContent = "blog_content"
	// FieldBlogAuthor holds the string denoting the blogauthor field in the database.
	FieldBlogAuthor = "blog_author"
	// Table holds the table name of the blogs in the database.
	Table = "blogs"
)

// Columns holds all SQL columns for blogs fields.
var Columns = []string{
	FieldID,
	FieldBlogTitle,
	FieldBlogType,
	FieldBlogContent,
	FieldBlogAuthor,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
