// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Blogs is the predicate function for blogs builders.
type Blogs func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
